#include "rocket_sil_framework/include/physics/simple_aerodynamics_model.hpp"

SimpleAerodynamicsModel::SimpleAerodynamicsModel(double drag_coefficient, double normal_force_coefficient, 
                                                 double reference_area_m2, double center_of_pressure_z,
                                                 double pitch_yaw_damping_coeff, double roll_damping_coeff)
    : drag_coefficient_(drag_coefficient), 
      normal_force_coefficient_(normal_force_coefficient),
      reference_area_(reference_area_m2),
      center_of_pressure_z_(center_of_pressure_z),
      pitch_yaw_damping_coeff_(pitch_yaw_damping_coeff),
      roll_damping_coeff_(roll_damping_coeff) {
}

AeroForces SimpleAerodynamicsModel::compute(const RocketState& state, const MassProperties& mass_props, const EnvironmentState& env) {
    AeroForces out;
    out.aerodynamic_force_body = Eigen::Vector3d::Zero();
    out.aerodynamic_moment_body = Eigen::Vector3d::Zero();

    // 1. Calculate relative airspeed (Inertial Frame)
    Eigen::Vector3d relative_velocity_inertial = state.velocity - env.wind_velocity_inertial;

    // Transform relative velocity to Body Frame
    Eigen::Vector3d velocity_body = state.orientation.inverse() * relative_velocity_inertial;
    
    double speed = velocity_body.norm();
    if (speed < 0.01) {
        return out; // Zbyt mała prędkość, siły aerodynamiczne pomijalne
    }

    // Ciśnienie dynamiczne (Dynamic pressure) q = 0.5 * rho * v^2
    double q_dyn = 0.5 * env.air_density * speed * speed;
        
        // --- 1. Siła Opóru (Drag Force) ---
        // Działa przeciwnie do wektora prędkości w układzie Body
        Eigen::Vector3d drag_dir_body = -velocity_body.normalized();
        double drag_magnitude = q_dyn * drag_coefficient_ * reference_area_;
        Eigen::Vector3d drag_force_body = drag_dir_body * drag_magnitude;
        
        // --- 2. Siła Nośna (Normal/Lift Force) ---
        // Zależna od kąta natarcia (Angle of Attack). 
        // Vz to prędkość wzdłużna (zakładamy oś Z jako główną oś rakiety od ogona do nosa).
        // Vx, Vy to prędkości poprzeczne wywołujące kąt natarcia.
        double v_transverse = std::sqrt(velocity_body.x() * velocity_body.x() + velocity_body.y() * velocity_body.y());
        double alpha = std::asin(v_transverse / speed); // Angle of attack
        
        // Normal force coefficient C_N = C_Na * alpha
        double cn = normal_force_coefficient_ * alpha;
        double normal_magnitude = q_dyn * cn * reference_area_;
        
        // Direction of normal force: opposite to transverse velocity
        Eigen::Vector3d normal_force_body = Eigen::Vector3d::Zero();
        if (v_transverse > 0.0001) {
            normal_force_body.x() = -velocity_body.x() / v_transverse * normal_magnitude;
            normal_force_body.y() = -velocity_body.y() / v_transverse * normal_magnitude;
        }

        out.aerodynamic_force_body = drag_force_body + normal_force_body;
        
        // --- 3. Aerodynamic Torque ---
        // Torque is generated by force applied at the Center of Pressure (CoP) 
        // around the Center of Gravity (CG).
        // Vector r: from CG to CoP
        Eigen::Vector3d cop_position(0.0, 0.0, center_of_pressure_z_);
        Eigen::Vector3d r_cg_to_cop = cop_position - mass_props.center_of_gravity;
        
        // Torque from normal force: tau = r x F
        Eigen::Vector3d aero_torque = r_cg_to_cop.cross(out.aerodynamic_force_body);
        
        // --- 4. Aerodynamic Damping ---
        // Damping increases with dynamic pressure (q_dyn) and angular velocity
        Eigen::Vector3d damping_torque;
        damping_torque.x() = -pitch_yaw_damping_coeff_ * q_dyn * state.angular_velocity.x();
        damping_torque.y() = -pitch_yaw_damping_coeff_ * q_dyn * state.angular_velocity.y();
        damping_torque.z() = -roll_damping_coeff_ * q_dyn * state.angular_velocity.z();
        
        out.aerodynamic_moment_body = aero_torque + damping_torque;

    return out;
}
